// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJBanDuKrT2aQ5h1iSUmP3OM0OaoBnn7Y',
    appId: '1:544047624810:web:c8c716f3f3997823091013',
    messagingSenderId: '544047624810',
    projectId: 'bmicalc-f7026',
    authDomain: 'bmicalc-f7026.firebaseapp.com',
    storageBucket: 'bmicalc-f7026.appspot.com',
    measurementId: 'G-N2LV5MJYCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeuB2ylJ2s3FVhwCpyjX0LI5lu3B0l8II',
    appId: '1:544047624810:android:1556f3126c0f9f5e091013',
    messagingSenderId: '544047624810',
    projectId: 'bmicalc-f7026',
    storageBucket: 'bmicalc-f7026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXwGcS2lEtU-9pyTJd2aj8KB3CuIxJYHw',
    appId: '1:544047624810:ios:6a8aa19de0c7f7b1091013',
    messagingSenderId: '544047624810',
    projectId: 'bmicalc-f7026',
    storageBucket: 'bmicalc-f7026.appspot.com',
    iosBundleId: 'com.example.bmiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXwGcS2lEtU-9pyTJd2aj8KB3CuIxJYHw',
    appId: '1:544047624810:ios:2a873715eef7b8aa091013',
    messagingSenderId: '544047624810',
    projectId: 'bmicalc-f7026',
    storageBucket: 'bmicalc-f7026.appspot.com',
    iosBundleId: 'com.example.bmiTest.RunnerTests',
  );
}
